[versions]
paper-api = "26.1.2.build.74-stable"
minecraft = "26.1.2"
mockbukkit = "4.115.0"
run-task = "3.1.0"
junit = "6.1.2"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v26.1.2", version.ref = "mockbukkit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
