blank_issues_enabled: true
contact_links:
  - name: BetterPlugin Documentation
    url: https://CoffeePopStudio.github.io/BetterPlugin/
    about: Please check the documentation before opening a usage question.
